### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexandrumatei36** [filecoin-shipyard/filecoin.js#1]
- [ ] keeping the source code and library documentation up to date with the latest Lotus changes
- [ ] add support for serializing BLS addresses. It may be implemented in the Zondax signing library and submit a PR if it is not in their short-term roadmap
- [ ] implement serialization as a general mechanism. for example, it’ll be necessary in the future when using smart contract methods
- [ ] store and download files using Filecoin.js. It will be implemented with support from the Lotus team. 
- [ ] implement a module to support general operations such as: address checks and validations, FIL conversions, large number helpers, string encoding helpers etc
- [ ] add a subscription module that contains high-level methods for managing long-term processes (synchronization, new block headers, wait for pending transactions, etc.)
- [ ] use multisig wallets and payment channels with external signers

**Comment by vasco-santos** [comment]
Hey @alexandrumatei36 
For what I can tell was implemented in #27 per #4. Is this assumption correct?
Can you let me know the state of the remaining items in this list?
